### ISSUE TITLE
Gitlab Webhooks

### ISSUE THREAD

**Issue by challapradyumna** [GrahamCampbell/Laravel-GitLab#16]
Are gitlab webhooks supported by the library? 
If not are there any plans to add support in future?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. There is nothing a library can do with helping webhook processing, mostly because it's actually nor needed. GitLab doesn't sign it's hooks, so it's as simple as just writing your own code to handle them.

In one of my apps, I just have a tiny controller method which does everything.

![image](https://user-images.githubusercontent.com/2829600/60998811-93de2b00-a351-11e9-9ebe-23dd228d11d3.png)

![image](https://user-images.githubusercontent.com/2829600/60998873-c0924280-a351-11e9-8ec7-edbbca2b9a42.png)

I hope this helps!

**Comment by GrahamCampbell** [comment]
Oh, yeh, and in terms of setting up webhooks, that part is supported by the library. It's available in the standard way, like the rest of the API. :)

**Comment by challapradyumna** [comment]
Thanks for the quick reply. I was thinking more in terms of easy handling of webhook requests, converting the JSON into a PHP Object. Also, getting more details about the project directly from the Webhook Object.

**Comment by GrahamCampbell** [comment]
>  converting the JSON into a PHP Object

`json_decode`
